### PR TITLE
WIP: Native CopyToCSV from sql databases

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by mrocklin** [comment]
Hrm interesting, so this effectively extends sqlalchemy a bit yes?  Do you think they would be interested in getting this upstream?

**Comment by cpcloud** [comment]
possibly. let me look around to see if anyone has attempted to get anything like this into sqlalchemy before

**Comment by cpcloud** [comment]
https://bitbucket.org/zzzeek/sqlalchemy/issue/3404/copy-to-csv-expression

I'll put this in the sqlalchemy wiki. No go on getting it in upstream.

**Comment by cpcloud** [comment]
merging. we can add more databases such as oracle piecemeal

**Pull request merged**
