### PR TITLE
Make sql<-csv converters robust to absence of sqlite3

### PR DESCRIPTION
**Pull request by mrocklin**
We've done this for Windows in the past.  Now we extend the
solution to other operating systems.

I honestly don't know how to test this well.  Perhaps the Anaconda
build system can help here.

cc @asmeurer

### CODE REVIEW

**Comment by cpcloud** [comment]
Is there no way we can list sqlite3 as a dependency only for windows?

**Comment by asmeurer** [comment]
I would rewrite this code to not use shell=True (can't you do this processing in Python?), and use `distutils.spawn.find_executable` or something similar to see if sqlite3 is there or not.

**Comment by cpcloud** [comment]
That way if someone installs blaze via conda then we can ensure that things are there.

**Comment by asmeurer** [comment]
Note that this problem will go away for conda based installations of odo because we are rebuilding the sqlite package with the sqlite3 binary (and sqlite is a dependency of Python itself, so it will always be there).

**Comment by cpcloud** [comment]
What versions of Python don't include SQLite?

**Comment by cpcloud** [comment]
Why does this need to be generalized? Is there an OS other than windows that has a python installation without SQLite?

**Comment by asmeurer** [comment]
For whatever reason, my stock ubuntu doesn't have the sqlite3 executable (but the system Python does seem to have the sqlite3 library). 

I don't know what the state of things would be on Windows. This issue originally came up on Ubuntu.

**Comment by mrocklin** [comment]
> I would rewrite this code to not use shell=True (can't you do this processing in Python?), and use distutils.spawn.find_executable or something similar to see if sqlite3 is there or not.

Now using `distutils.spawn.find_executable`.  I'm pretty ignorant on the best approach here.  Quite happy to learn of better ways.

**Comment by asmeurer** [comment]
The better approach is to avoid using `shell=True`. Split the command in a list and pass it to subprocess. `shell=True` leads to pretty bad shell injection vulnerabilities (if someone can use an arbitrary string as one of the variables, then they can trivially execute arbitrary shell commands). I would also replace all the shell piping Python (or at least separate subprocess calls). It's much easier to maintain Python than a shell oneliner. 

This is independent of this fix, though. I would just test that this works (remove sqlite from your PATH and run the tests).

**Comment by mrocklin** [comment]
Verified that this works when sqlite3 is missing.  Merging.

**Pull request merged**
