### PR TITLE
Add a default of None when going from records to tuples

### LINKED ISSUE #227: JSON <-> CSV keyerror
Hello,

I am trying to use odo to convert a JSON log to CSV, the problem is, that half of my JSON-lines miss the "source_allocated"-key-value-pair, so the discovery works fine:

    odo.discover(odo.resource('jsonlines://events.json'))
    dshape("""var * {
      feed: string,
      feed_url: string,
      observation_time: datetime,
      reported_source_ip: string,
      source_allocated: ?date,
      source_as_name: string,
      [...]
      }""")

But running the migration to CSV, fails with a keyerror:

    odo.odo('jsonlines://events.json', 'events.csv')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/odo/odo.py", line 90, in odo
        return into(target, source, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/multipledispatch/dispatcher.py", line 163, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/odo/into.py", line 120, in into_string_string
        return into(a, r, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/multipledispatch/dispatcher.py", line 163, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/odo/into.py", line 114, in into_string
        return into(a, b, dshape=ds, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/multipledispatch/dispatcher.py", line 163, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/odo/into.py", line 100, in into_object
        return append(target, source, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/multipledispatch/dispatcher.py", line 163, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/odo/backends/csv.py", line 75, in append_object_to_csv
        append(c, convert(chunks(pd.DataFrame), seq, **kwargs), **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/odo/core.py", line 30, in __call__
        return _transform(self.graph, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/odo/core.py", line 46, in _transform
        x = f(x, excluded_edges=excluded_edges, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/odo/convert.py", line 208, in iterator_to_DataFrame_chunks
        df = convert(pd.DataFrame, first, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/odo/core.py", line 30, in __call__
        return _transform(self.graph, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/odo/core.py", line 46, in _transform
        x = f(x, excluded_edges=excluded_edges, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/odo/convert.py", line 165, in list_to_numpy
        seq = list(records_to_tuples(dshape, seq))
    KeyError: u'source_allocated'

I guess this is my fault, yet my question is, are there possibilities to run odo in a more fault-tolerant way, so this would just be skipped by creating an empty cell in CSV?

### PR DESCRIPTION
**Pull request by cpcloud**
closes #227

### CODE REVIEW

**Comment by cpcloud** [comment]
@llllllllll can you give this a quick review when you get a chance?

**Comment by llllllllll** [comment]
lgtm!

**Comment by cpcloud** [comment]
yeah, let me add that test

**Comment by cpcloud** [comment]
Merging on pass

**Pull request merged**
