### PR TITLE
URL on top of #167

### PR DESCRIPTION
**Pull request by cpcloud**
adds more robust encoding and removes duplicate newlines from a text file when generating a sample

### CODE REVIEW

**Comment by cpcloud** [comment]
Actually, I don't think the `TextFile` support here is necessary. It's always discovered as `var * string`

**Comment by cpcloud** [comment]
@quasiben put tests in that pass when `URL(TextFile)` isn't in the signatures inside of `sample` and `discover` in `url.py`

**Comment by cpcloud** [comment]
I also think this is a backend that will work without any deps, because we're only using stdlib stuff.

**Comment by cpcloud** [comment]
hm maybe not. we use `csv` in it

**Comment by cpcloud** [comment]
@quasiben you're next in the PR queue after #173 -> #172 -> #168

**Comment by quasiben** [comment]
:)

**Comment by cpcloud** [comment]
merging soon, just want to confirm that current binstar builds are passing, then will merge

**Pull request merged**
