### PR TITLE
missing }

### PR DESCRIPTION
**Pull request by gwulfs**

### CODE REVIEW

**Comment by llllllllll** [comment]
Thanks for the fix, let me just see what is up with the build failure before merging; however, I am not sure how this would trigger the failure.

**Comment by cpcloud** [comment]
Looks like a new release of pytables broke something in pandas

**Comment by cpcloud** [comment]
Actually this was our fault, we have true division enabled and a chunksize was getting passed as `2.0` and casting to long when slicing a pytables `Table` was removed in the latest pytables. Fixed in #236

**Comment by cpcloud** [comment]
@gwulfs Can you pull from master and push up again to rerun against the fix i put in in #236

**Pull request closed without merging**
